
os: linux
dist: bionic
language: generic

install:
  - export DOCKER_IMAGE=osrf/ros2:nightly
  - export CI_SOURCE_PATH=$(pwd)
  - export REPO_NAME=${PWD##*/}
  
  - docker run -v $HOME:$HOME -e CI_SOURCE_PATH -e $REPO_NAME -e HOME $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_PATH; source .github/travis.sh'
